# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='location',
            new_name='tweeted_at',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_json',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
