# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterData', '0002_auto_20160213_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
