# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterData', '0003_auto_20160213_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
